import { redirect } from "next/navigation";
import { Icon } from "@/components/icon";
import { Logo } from "@/components/logo";
import { getCurrentUser } from "@/lib/auth";
import { LoginForm } from "./login-form";

export default async function LoginPage() {
  if (await getCurrentUser()) redirect("/dashboard");
  return <main className="grid min-h-screen bg-slate-50 lg:grid-cols-[1.08fr_.92fr]"><section className="relative hidden overflow-hidden bg-[#063f3d] p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-32 -top-32 size-[500px] rounded-full border border-white/10"/><div className="absolute -right-12 -top-12 size-[320px] rounded-full border border-white/10"/><div className="relative"><div className="inline-flex rounded-xl bg-white p-1"><Logo /></div></div><div className="relative max-w-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.24em] text-teal-200">A warmer welcome, with less paperwork</p><h1 className="text-5xl font-semibold leading-[1.08] tracking-[-.04em]">Every arrival,<br/>beautifully organized.</h1><p className="mt-6 max-w-md text-base leading-7 text-teal-50/70">Register visitors, keep hosts informed, and understand who is on site—all from one calm workspace.</p></div><div className="relative grid grid-cols-3 gap-3">{[{ icon: "shield" as const, label: "Secure access" }, { icon: "clock" as const, label: "Live status" }, { icon: "reports" as const, label: "Clear reports" }].map((item) => <div key={item.label} className="rounded-xl border border-white/10 bg-white/[.06] p-4"><Icon name={item.icon} className="mb-3 size-5 text-teal-200"/><p className="text-xs font-semibold text-white/80">{item.label}</p></div>)}</div></section><section className="flex items-center justify-center p-6 sm:p-12"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Logo /></div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">Welcome back</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Sign in to Visentry</h2><p className="mt-2 text-sm leading-6 text-slate-500">Use your assigned account to continue to your workspace.</p><LoginForm /><div className="mt-8 rounded-xl border border-slate-200 bg-white p-4 text-xs leading-5 text-slate-500"><p className="font-semibold text-slate-700">Demo access</p><p className="mt-1">Try <strong>reception@acme.demo</strong> with password <strong>Demo@123</strong>.</p></div><p className="mt-7 text-center text-xs text-slate-400">Protected with secure, revocable sessions</p></div></section></main>;
}
