import { changePasswordAction, logoutAction } from "@/app/actions";
import { ActionForm, SubmitButton } from "@/components/action-form";
import { Icon } from "@/components/icon";
import { PageHeader } from "@/components/page-header";
import { requireUser } from "@/lib/auth";
import { initials, roleLabel } from "@/lib/format";

export default async function ProfilePage() {
  const user = await requireUser();
  return <>
    <PageHeader eyebrow="Account" title="My profile" description="Review your workspace identity and keep your password secure."/>
    <div className="grid gap-6 lg:grid-cols-[340px_1fr]">
      <section className="panel p-6 text-center"><span className="mx-auto grid size-20 place-items-center rounded-2xl bg-teal-50 text-xl font-bold text-teal-700">{initials(user.name)}</span><h2 className="mt-4 text-lg font-bold text-slate-900">{user.name}</h2><p className="mt-1 text-sm text-slate-500">{user.email}</p><span className="status-badge green mt-4"><span className="status-dot"/>{roleLabel(user.role)}</span><form action={logoutAction} className="mt-6"><button className="button secondary w-full"><Icon name="logout" className="size-4"/>Log out securely</button></form></section>
      <div className="space-y-6">
        <section className="panel"><div className="panel-header"><div><h2 className="panel-title">Account details</h2><p className="panel-subtitle">Contact an administrator if these details need updating</p></div></div><dl className="grid gap-px bg-slate-100 sm:grid-cols-2"><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Full name</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{user.name}</dd></div><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Email</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{user.email}</dd></div><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Company</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{user.company?.name ?? "System-wide access"}</dd></div><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Role</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{roleLabel(user.role)}</dd></div>{user.staffProfile && <><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Department</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{user.staffProfile.department}</dd></div><div className="bg-white p-5"><dt className="text-[10px] font-bold uppercase tracking-[.12em] text-slate-400">Phone</dt><dd className="mt-2 text-sm font-semibold text-slate-800">{user.staffProfile.phone ?? "Not provided"}</dd></div></>}</dl></section>
        <section className="panel"><div className="panel-header"><div><h2 className="panel-title">Change password</h2><p className="panel-subtitle">Other signed-in sessions will be closed</p></div><span className="metric-icon text-teal-700"><Icon name="shield" className="size-[18px]"/></span></div><ActionForm action={changePasswordAction} className="grid gap-4 p-5 sm:grid-cols-2"><label className="field sm:col-span-2"><span>Current password *</span><input name="currentPassword" type="password" autoComplete="current-password" required/></label><label className="field"><span>New password *</span><input name="newPassword" type="password" autoComplete="new-password" minLength={8} required placeholder="8+ characters"/></label><label className="field"><span>Confirm new password *</span><input name="confirmPassword" type="password" autoComplete="new-password" minLength={8} required/></label><div className="sm:col-span-2"><p className="mb-3 text-[11px] text-slate-400">Use at least 8 characters with a letter and a number.</p><SubmitButton>Update password</SubmitButton></div></ActionForm></section>
      </div>
    </div>
  </>;
}
